### ISSUE TITLE
inventory UI clickthrough not completely gone in editor

### ISSUE THREAD

**Issue by smjjames** [ihsoft/KIS#33] opened 2015-04-06 15:44 UTC
I'm noticing that when in editor and you attempt to left click+drag on one of the inventory boxes (it's the same whether the inventory box has something in it or not) of a container and you mouse over a ship part when you release the mouse button, you'll grab and move the ship part. Definetly better than before where you'd click right through, but still a problem.

It also happens when you click the close button and the mouse happens to be over a ship part, you'll instantly left click and remove the part at the same time as it closes.

Edit: The old KAS edit container UI actually has the same problem with the close button where if it's over a part when you click the button, you'll also click on the part an instant after. The KAS UI is so big though that the button is generally out of the way.

**Comment by KospY** [comment] 2015-04-17 22:20
Didn't have this problem, did you try with the latest version ?

**Comment by smjjames** [comment] 2015-04-18 22:18
Yes, that was with 1.0.2.

May have something to do with me using a touchpad mouse since it's a laptop, no idea.

**Comment by KospY** [comment] 2015-04-20 10:32
This is strange... No one else reporting me this issue. Maybe try with a mouse ?

**Comment by smjjames** [comment] 2015-04-20 16:08
I don't have a regular mouse though.

**Comment by KospY** [comment] 2015-05-26 13:58
Closing this issue as I cannot reproduce it and nobody else seem to have this problem.

**Closed as completed by KospY** 2015-05-26 13:58 UTC
Labels: wontfix
