### ISSUE TITLE
maxVolume = 0 in ModuleKISInventory config breaks inventory in editor

### ISSUE THREAD

**Issue by shadowmage45** [ihsoft/KIS#228] opened 2017-09-23 01:33 UTC
Setting 'maxVolume = 0' in the ModuleKISInventory configuration results in an unusable inventory while in the editor.  The inventory button reads 'Seat 0 Inventory' even on parts without crew capacity.  Even if the volume is later increased (through external mod code), any parts placed into the inventory are lost when the craft is launched into the flight scene.

If the ModuleKISInventory config has a maxVolume > 0 specified, the part functions normally in the editor.  Even if the maxVolume is later reduced to 0 through external code, the inventory still functions properly in the editor.

Can be duplicated when the following patch is used to add the ModuleKISInventory to the stock FLT-100 fuel tank (or any other part):
````
@PART[fuelTankSmallFlat]:NEEDS[KIS]
{	
	MODULE
	{
		name = ModuleKISInventory
		maxVolume = 0
		externalAccess = true
		internalAccess = true
		slotsX = 4
		slotsY = 4
		slotSize = 50
		itemIconResolution = 128
		selfIconResolution = 128
		openSndPath = KIS/Sounds/containerOpen
		closeSndPath = KIS/Sounds/containerClose
		defaultMoveSndPath = KIS/Sounds/itemMove
	}
}
````
Results in:
![screenshot3](https://user-images.githubusercontent.com/1503399/30768815-0984123e-9fcb-11e7-822a-44ea051e86eb.png)

Full log file:
[KSP.log](https://github.com/ihsoft/KIS/files/1326173/KSP.log)
[output_log.txt](https://github.com/ihsoft/KIS/files/1326178/output_log.txt)

(will try to upload a cleaner log without all the other mods' spam in it)

System Specs:
i5-2500k - 24gb DDR3 - GTX970 - Win10-64bit
Using steam version of KSP, 64bit, copied/relocated for dev work, located in F:/KSP130/

Please let me know if there was any further information I can provide.

**Comment by ihsoft** [comment] 2017-09-23 03:55
It doesn't reproduce to me:
![image](https://user-images.githubusercontent.com/7295777/30769915-b70acaf4-9fd7-11e7-91fc-98f7821d47a1.png)

Looks like there is another mod that causes it. Try removing all the mods but KIS, and repeat the testing.

**Comment by shadowmage45** [comment] 2017-09-24 16:11
Interesting indeed -- I'll make a clean 1.30 install with just KIS + dependencies and see if I can repro it there.

**Comment by ihsoft** [comment] 2017-11-18 22:28
Closing it for now. Feel free to reopen if there are more details.

**Closed as completed by ihsoft** 2017-11-18 22:28 UTC
Labels: Need testing
