### ISSUE TITLE
Ground Base keeps detaching from ground

### ISSUE THREAD

**Issue by ranathane** [ihsoft/KIS#78] opened 2015-07-24 06:29 UTC
When a physics reload occurs, sometimes the Ground Base pops off the surface (Mun and Minmus ground) detaching anything connected to it.

**Comment by ranathane** [comment] 2015-07-25 11:45
Further details:

When physics refresh happens and anything is connected with a pipe (via connector), there is a chance (unknown what the percentage is) that the item the connector is connected to will 'jump' in the air. If the acceleration is too high (I think) this causes a disconnect of any parts connected to it other than landing legs. I had switched from using the concrete base as my ground connector to the Small Ore Tank with 3 of the medium landing legs. When adding/removing the link one or more of the other linked sections will 'jump' up. (http://steamcommunity.com/id/ranathane/screenshots/?appid=220200)
I can provide a save game if needed.

**Comment by KospY** [comment] 2015-07-31 12:24
I will need more information.
Can you provide your save game please ?

**Comment by DrLuke** [comment] 2015-09-15 20:21
This happened to me aswell.

**Comment by wolby2010** [comment] 2015-12-09 13:03
I had an issue similar to yours where I had lots of pipes and ground connectors and then I quick-saved and I did something dumb so I loaded the quicksave and found that some of the connectors had disconnected themselves and were marked as debris. I EVA'd so I could repair it but every time I tried to grab one of these disconnected parts they would spontaneously combust causing the KIS attach dialogue to remain with no fix except for restarting KSP

**Comment by ihsoft** [comment] 2016-02-19 09:28
Yeah, I saw this happening couple of times too. No clue why, though. Any input on how to reproduce the issue is welcome.

**Comment by ihsoft** [comment] 2016-06-07 08:25
As for now it only happens on a long bases. Breaking force accumulates thru the parts and, eventually, break either pipe connection or pylon attachment. The only way to fix it at this moment is not attaching to the ground all the pylons in the path, and only attach one to anchor the base.

Solution to the issue would be introducing a flexible pipe which will be able to discharge the accumulated stress. It's a future feature of KAS.

**Closed as completed by ihsoft** 2016-06-07 08:25 UTC
Labels: wontfix
