### ISSUE TITLE
Laboratories can't be added to inventory

### ISSUE THREAD

**Issue by bwucke** [ihsoft/KIS#174] opened 2016-09-25 00:53 UTC
Regardless of the amount of space in the container, laboratory modules (stock lab, and modded) cannot be added to inventory. The game just silently refuses to add a lab dropped into the container. 

Not such a big problem in VAB where "why would you ever want to put a lab in a box?" but if you build a lab with e.g. OSE Workshop, the pipeline gets permanently clogged as the workshop is unable to add the finished lab to a container, halting any production and requiring unclogging through manually editing the save.

Interestingly, the lab can't be added in VAB or SPH, or through the workshop, but four kerbals on EVA have no problem carrying it to the container and putting it inside.

**Comment by ihsoft** [comment] 2016-09-25 01:21
Duplicate of #157

**Closed as completed by ihsoft** 2016-09-25 01:21 UTC
Labels: duplicate
