### ISSUE TITLE
Kerbals can'y pull items from Inventories

### ISSUE THREAD

**Issue by crazygreek** [ihsoft/KIS#131] opened 2016-05-02 12:53 UTC
Any item stored in an inventory throws a "Too heavy, bring more kerbals [x.xx > 0.00]"
Weight of kerbal EVA (1.00) is not recognized. (Other nearby kerbals also not recognized)
Items can be moved into inventories as normal

**Comment by Jajcus** [comment] 2016-05-02 15:03
Same here, after todays update. KSP 1.1.2, KIS 1.2.8.

Downgrading KIS to 1.2.7 fixed the problem.

~~No, it didn't. The improvement was only temporary. My Kerbals refuse to move anything heavier than '0.000t' again.~~

**Comment by ihsoft** [comment] 2016-05-02 17:34
So, you reverted to 1.2.7 and the problem is still there? It looks like a mods conflict then. Inventory mass checking was introduced in 1.2.8.

**Comment by labo-css** [comment] 2016-05-02 20:02
Got the same bug, replicable ad infinitum. The entiere mod is broken to me

**Comment by Jajcus** [comment] 2016-05-02 20:31
@ihsoft hmm… maybe I did the downgrade wrong. I'll try again.

**Comment by crazygreek** [comment] 2016-05-02 21:18
Can confirm TweakScale causes the issue, Can we make a version where the inv mass check is omitted as a temp fix untill the issue is resolved ?

**Comment by Dahlgaard** [comment] 2016-05-02 21:18
Hi
I'm experiencing the same issue. I've posted on the kerbal forums, but since it's a new account there the post isn't visible until a moderator approves it. 

I'm getting the same issue with version 1.2.8 of KIS: "Too heavy, bring more kerbal [_object mass here_ > 0.000t]".
I tried installing KIS v1.2.8 and the new version of KAS into a unmodded version of KSP 1.1.2 to see if the problem appears there when only KIS/KAS is installed, and if i do that it works without problems! So i went conflict hunting. I have a long list of mods so i cant say for sure if more than one is causing a problem but one that definitely did cause this to happen for me is installing KIS/KAS along side TweakScale. 

Once i put TweakScale into the same KSP install with just KIS/KAS that worked a minute before, it breaks and produces the mentioned error when trying to pull things from inventory.

Any chance of an update to KIS/KAS? Or is this something that has to be fixed in TweakScale?

My version of TweakScale: v2.2.9.
http://forum.kerbalspaceprogram.com/index.php?/topic/101540-112-tweakscale-v229apr-30-fixes-and-recompile/

**Comment by ihsoft** [comment] 2016-05-02 22:19
TweakScale is known to make troubles to KIS but before it was about wrong mass/volume only. I'll investigate it to see if this can be fixed. Thanks for the info about conflicting mod, it really helps.

**Comment by kris-kb** [comment] 2016-05-02 22:54
I don't use TweakScale and i got the same bug , However i got some other mods installed.
SCANsat 
PlanetShine
PlanetaryBase
TextureReplacer
And Kis & Kas of course.

**Comment by MechWorks** [comment] 2016-05-02 23:17
confirming it's not just Tweakscale causing issues, I am not using it but am having the same issue-
I have a somewhat extensive modlist, but THIS looks like your problem child:


[ERR 16:02:07.712] Input is null
   at System.Environment.get_StackTrace()
   at ConfigNode.CleanupInput(System.String value)
   at ConfigNode.AddValue(System.String name, System.String value)
   at BaseFieldList.Save(.ConfigNode node)
   at PartModule.Save(.ConfigNode node)
   at ProtoPartModuleSnapshot..ctor(.PartModule module)
   at ProtoPartSnapshot..ctor(.Part PartRef, .ProtoVessel protoVessel)
   at ProtoVessel..ctor(.Vessel VesselRef)
   at Vessel.BackupVessel()
   at FlightState..ctor()
   at Game.Updated()
   at PauseMenu.<draw>m__83A()
   at DialogGUIButton.OptionSelected()
   at DialogGUIButton.<Create>m__827()
   at UnityEngine.Events.InvokableCall.Invoke(System.Object[] args)
   at UnityEngine.Events.InvokableCallList.Invoke(System.Object[] parameters)
   at UnityEngine.Events.UnityEventBase.Invoke(System.Object[] parameters)
   at UnityEngine.Events.UnityEvent.Invoke()
   at UnityEngine.UI.Button.Press()
   at UnityEngine.UI.Button.OnPointerClick(UnityEngine.EventSystems.PointerEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute(IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData)
   at UnityEngine.EventSystems.ExecuteEvents.Execute(UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor)
   at UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress(UnityEngine.EventSystems.MouseButtonEventData data)
   at UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent(Int32 id)
   at UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent()
   at UnityEngine.EventSystems.StandaloneInputModule.Process()
   at UnityEngine.EventSystems.EventSystem.Update()
appears when I tried to attach the stake to something.

**Comment by ihsoft** [comment] 2016-05-02 23:41
I don't see KIS in the stack trace. It may get triggered by KIS but it doesn't seem to be a reson of this particular bug. Please, create a spearate one with this stack trace. And give exact steps and mods to reproduce it. All such errors are related to specific part's modules. I'm pretty sure you won't see this error on a clear game.

**Closed as completed** 2016-05-03 06:23 UTC
Labels: bug
