### ISSUE TITLE
Clicking problem in VAB..

### ISSUE THREAD

**Issue by cookins** [ihsoft/KIS#51] opened 2015-05-15 10:11 UTC
I have issue with clicking problem over parts selection in VAB.. Sometimes I need to press 3-4 times to select part over left side parts selection window. Not only me have such issue.
Here link on kerbal forums to same issue (started by me) - http://forum.kerbalspaceprogram.com/threads/121339-Parts-selection-in-VAB-issue
Thanks!

**Comment by enceos** [comment] 2015-05-19 03:26
The problem is you move your mouse while clicking. When you move your mouse during the click, KIS goes into the item drag mode. To take a part from the list just hold your mouse still.

The solution would be to make KIS go to the drag mode only after 10 pixels of mouse movement while the left mouse button is held. I don't know if it's possible at all.

**Comment by KospY** [comment] 2015-05-26 08:04
Seem like the problem is fixed in the thread. I'm closing this issue.

**Closed as completed by KospY** 2015-05-26 08:04 UTC
Labels: wontfix
