### ISSUE TITLE
EAS-1 External Command Seat loses icon

### ISSUE THREAD

**Issue by Goldenpsp** [ihsoft/KIS#41] opened 2015-05-07 13:21 UTC
You can move the command seat into a storage container but it loses its icon.  You can interact with it and later remove it from the container, but while it is in the container it is invisible.  You can hover over the inventory and see that it is there from the tooltip pop on mouseover, just not the icon.

**Comment by Gobur** [comment] 2015-05-08 09:13
Is similar problem with seat from USI Exploration Pack

**Comment by KospY** [comment] 2015-05-15 09:40
It's a KSP related bug. You can check this ingame : the command seat tooltip icon are empty too. 
I currently use icons generated by KSP.
I'm waiting Squad to fix this issue.

**Comment by mongoose11235813** [comment] 2015-07-23 08:16
I made some research.
Here is the result:
1. The problem is caused by a shader. Broken shader: KSP/Alpha/Cutoff
2. This shader is used in a few of places here and there but the command seat is the only part that doesn't have other shaders.
3. Another part where the problem is noticeable but not fatal is a launch clamp:
![notlethal](https://cloud.githubusercontent.com/assets/13386246/8845998/369ad420-312c-11e5-9aa4-bd870e25a8ce.png)

**Comment by mongoose11235813** [comment] 2015-07-26 18:33
I managed to fix it. I'll upload my fix soon:
![image](https://cloud.githubusercontent.com/assets/13386246/8895302/e404a614-33dd-11e5-81d5-65e2c5da57cf.png)

**Comment by mongoose11235813** [comment] 2015-07-26 21:27
My repository: https://github.com/mongoose11235813/CommandSeatIconFix/releases
Download fix: https://github.com/mongoose11235813/CommandSeatIconFix/releases/tag/0.1

**Comment by KospY** [comment] 2015-07-30 12:45
@mongoose11235813 : Nice one! So the problem is caused by a shader!

As squad didn't seem to fix this issue, I implemented in the KIS iconviewer class the shader change for the command seat icon (this way I didn't touch to squad parts prefab).
Here is the commit : https://github.com/KospY/KIS/commit/9d0b1505797ff900c9ff85485356221e21ded2cc. This will be included in the next version of KIS.
Many many thanks for your help :)

**Comment by mongoose11235813** [comment] 2015-07-30 19:02
> Thank you

Not at all
BTW I'd recommend you a slightly different approach (#80) because some modded parts (e.g. USI rover seat) are using this shader too.

**Closed as completed** 2016-02-19 09:30 UTC
Labels: Fixed (next version)
